# Generated by Django 2.1 on 2018-08-21 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_auto_20180821_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ('created_at',), 'verbose_name_plural': 'providers'},
        ),
    ]
