# Generated by Django 2.1 on 2018-08-21 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0004_auto_20180821_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provider.Provider'),
        ),
    ]
